use crate::domain::models::{
    BanRecord, Community, OperationLog, SeedData, Server, ServerPlayer, UserSummary, WebsiteAdmin,
    WhitelistPlayer,
};

pub(crate) fn users_summary() -> UserSummary {
    UserSummary {
        enabled: false,
        message: "网站用户模块待开发".to_string(),
        planned_modules: vec![
            "网站管理员账号体系".to_string(),
            "社区负责人角色权限".to_string(),
            "玩家个人中心与白名单申请入口".to_string(),
            "登录、鉴权与操作日志".to_string(),
        ],
    }
}

pub(crate) fn seed_data() -> SeedData {
    SeedData {
        communities: vec![
            Community {
                id: "community_hightower".to_string(),
                name: "HighTower KZ 社区".to_string(),
                created_at: "2026-03-06T12:00:00.000Z".to_string(),
                servers: vec![Server {
                    id: "server_hightower_1".to_string(),
                    name: "Hightower #1 Beginner".to_string(),
                    ip: "45.32.18.20".to_string(),
                    port: 27015,
                    rcon_password: "rcon-demo-01".to_string(),
                    rcon_verified_at: "2026-03-06T12:05:00.000Z".to_string(),
                    whitelist_enabled: true,
                    entry_verification_enabled: false,
                    online_players: vec![
                        ServerPlayer {
                            id: "player_srv_001".to_string(),
                            nickname: "KZRunner".to_string(),
                            steam_id: "STEAM_1:1:120001".to_string(),
                            ip_address: "203.0.113.21".to_string(),
                            connected_at: "2026-03-07T09:15:00.000Z".to_string(),
                            ping: 32,
                        },
                        ServerPlayer {
                            id: "player_srv_002".to_string(),
                            nickname: "LongJump".to_string(),
                            steam_id: "STEAM_1:0:889911".to_string(),
                            ip_address: "203.0.113.34".to_string(),
                            connected_at: "2026-03-07T09:22:00.000Z".to_string(),
                            ping: 48,
                        },
                    ],
                }],
            },
            Community {
                id: "community_skyline".to_string(),
                name: "Skyline Climb 社区".to_string(),
                created_at: "2026-03-05T08:30:00.000Z".to_string(),
                servers: vec![
                    Server {
                        id: "server_skyline_1".to_string(),
                        name: "Skyline #2 Pro".to_string(),
                        ip: "103.21.244.88".to_string(),
                        port: 27016,
                        rcon_password: "rcon-demo-02".to_string(),
                        rcon_verified_at: "2026-03-05T09:00:00.000Z".to_string(),
                        whitelist_enabled: false,
                        entry_verification_enabled: true,
                        online_players: vec![ServerPlayer {
                            id: "player_srv_003".to_string(),
                            nickname: "CliffSide".to_string(),
                            steam_id: "STEAM_1:0:901245".to_string(),
                            ip_address: "198.51.100.16".to_string(),
                            connected_at: "2026-03-07T08:58:00.000Z".to_string(),
                            ping: 67,
                        }],
                    },
                    Server {
                        id: "server_skyline_2".to_string(),
                        name: "Skyline #3 Fastcup".to_string(),
                        ip: "103.21.244.89".to_string(),
                        port: 27017,
                        rcon_password: "rcon-demo-03".to_string(),
                        rcon_verified_at: "2026-03-05T09:10:00.000Z".to_string(),
                        whitelist_enabled: true,
                        entry_verification_enabled: true,
                        online_players: vec![
                            ServerPlayer {
                                id: "player_srv_004".to_string(),
                                nickname: "WallBug".to_string(),
                                steam_id: "STEAM_1:1:765432".to_string(),
                                ip_address: "198.51.100.72".to_string(),
                                connected_at: "2026-03-07T09:05:00.000Z".to_string(),
                                ping: 54,
                            },
                            ServerPlayer {
                                id: "player_srv_005".to_string(),
                                nickname: "SpeedArc".to_string(),
                                steam_id: "STEAM_1:0:445566".to_string(),
                                ip_address: "192.0.2.55".to_string(),
                                connected_at: "2026-03-07T09:11:00.000Z".to_string(),
                                ping: 41,
                            },
                        ],
                    },
                ],
            },
        ],
        whitelist: vec![
            WhitelistPlayer {
                id: "player_approved_1".to_string(),
                nickname: "KZRunner".to_string(),
                steam_id: "STEAM_1:1:120001".to_string(),
                contact: Some("qq: 223344".to_string()),
                note: Some("比赛服常驻玩家".to_string()),
                status: "approved".to_string(),
                source: "manual".to_string(),
                applied_at: "2026-03-04T13:10:00.000Z".to_string(),
                reviewed_at: Some("2026-03-04T14:20:00.000Z".to_string()),
            },
            WhitelistPlayer {
                id: "player_pending_1".to_string(),
                nickname: "LongJump".to_string(),
                steam_id: "STEAM_1:0:889911".to_string(),
                contact: Some("discord: longjump".to_string()),
                note: Some("申请进入训练服".to_string()),
                status: "pending".to_string(),
                source: "application".to_string(),
                applied_at: "2026-03-06T10:15:00.000Z".to_string(),
                reviewed_at: None,
            },
            WhitelistPlayer {
                id: "player_pending_2".to_string(),
                nickname: "CliffSide".to_string(),
                steam_id: "STEAM_1:0:901245".to_string(),
                contact: Some("qq: 556677".to_string()),
                note: Some("新玩家，等待审核".to_string()),
                status: "pending".to_string(),
                source: "application".to_string(),
                applied_at: "2026-03-06T11:20:00.000Z".to_string(),
                reviewed_at: None,
            },
            WhitelistPlayer {
                id: "player_rejected_1".to_string(),
                nickname: "WallBug".to_string(),
                steam_id: "STEAM_1:1:765432".to_string(),
                contact: Some("qq: 889900".to_string()),
                note: Some("资料不完整".to_string()),
                status: "rejected".to_string(),
                source: "manual".to_string(),
                applied_at: "2026-03-03T15:40:00.000Z".to_string(),
                reviewed_at: Some("2026-03-03T16:00:00.000Z".to_string()),
            },
        ],
        bans: vec![
            BanRecord {
                id: "ban_001".to_string(),
                nickname: Some("WallBug".to_string()),
                ban_type: "steam_account".to_string(),
                status: "active".to_string(),
                steam_identifier: "STEAM_1:1:765432".to_string(),
                steam_id64: "76561197961796593".to_string(),
                steam_id: "STEAM_1:1:765432".to_string(),
                steam_id3: "[U:1:1530865]".to_string(),
                ip_address: Some("198.51.100.72".to_string()),
                reason: "多次利用漏洞干扰服务器秩序".to_string(),
                duration_seconds: None,
                banned_at: "2026-03-06T12:40:00.000Z".to_string(),
                server_name: "Skyline #3 Fastcup".to_string(),
                community_name: Some("Skyline Climb 社区".to_string()),
                operator_id: "admin_ops".to_string(),
                operator_name: "运营管理员".to_string(),
                operator_role: "normal_admin".to_string(),
                source: "server_action".to_string(),
                updated_at: Some("2026-03-06T12:40:00.000Z".to_string()),
                revoked_at: None,
                revoked_by_operator_id: None,
                revoked_by_operator_name: None,
                revoked_by_operator_role: None,
            },
            BanRecord {
                id: "ban_002".to_string(),
                nickname: None,
                ban_type: "ip".to_string(),
                status: "active".to_string(),
                steam_identifier: "https://steamcommunity.com/profiles/76561197960505731"
                    .to_string(),
                steam_id64: "76561197960505731".to_string(),
                steam_id: "STEAM_1:1:120001".to_string(),
                steam_id3: "[U:1:240003]".to_string(),
                ip_address: None,
                reason: "恶意刷屏与骚扰其他玩家".to_string(),
                duration_seconds: Some(86400),
                banned_at: "2026-03-07T01:15:00.000Z".to_string(),
                server_name: "手动录入（未关联服务器）".to_string(),
                community_name: None,
                operator_id: "admin_root".to_string(),
                operator_name: "主系统管理员".to_string(),
                operator_role: "system_admin".to_string(),
                source: "manual".to_string(),
                updated_at: Some("2026-03-07T01:15:00.000Z".to_string()),
                revoked_at: None,
                revoked_by_operator_id: None,
                revoked_by_operator_name: None,
                revoked_by_operator_role: None,
            },
        ],
        admins: vec![
            WebsiteAdmin {
                id: "admin_root".to_string(),
                username: "root_admin".to_string(),
                display_name: "主系统管理员".to_string(),
                role: "system_admin".to_string(),
                password: "Admin@123".to_string(),
                email: Some("root@kzguard.local".to_string()),
                note: Some("拥有网站全部权限，可维护其他管理员账号。".to_string()),
                created_at: "2026-03-06T09:00:00.000Z".to_string(),
                updated_at: "2026-03-06T09:00:00.000Z".to_string(),
            },
            WebsiteAdmin {
                id: "admin_ops".to_string(),
                username: "ops_manager".to_string(),
                display_name: "运营管理员".to_string(),
                role: "normal_admin".to_string(),
                password: "Ops@1234".to_string(),
                email: Some("ops@kzguard.local".to_string()),
                note: Some("负责日常社区与白名单审核。".to_string()),
                created_at: "2026-03-06T09:10:00.000Z".to_string(),
                updated_at: "2026-03-06T09:10:00.000Z".to_string(),
            },
            WebsiteAdmin {
                id: "admin_review".to_string(),
                username: "review_guard".to_string(),
                display_name: "审核管理员".to_string(),
                role: "normal_admin".to_string(),
                password: "Review@123".to_string(),
                email: Some("review@kzguard.local".to_string()),
                note: Some("负责玩家申请初审与记录维护。".to_string()),
                created_at: "2026-03-06T09:20:00.000Z".to_string(),
                updated_at: "2026-03-06T09:20:00.000Z".to_string(),
            },
        ],
        operation_logs: vec![
            OperationLog {
                id: "log_001".to_string(),
                created_at: "2026-03-06T09:35:00.000Z".to_string(),
                operator_id: "admin_root".to_string(),
                operator_name: "主系统管理员".to_string(),
                operator_role: "system_admin".to_string(),
                action: "admin_profile_updated".to_string(),
                detail: "修改了 运营管理员 的备注信息，用于明确其负责社区与白名单日常维护。"
                    .to_string(),
            },
            OperationLog {
                id: "log_002".to_string(),
                created_at: "2026-03-06T10:10:00.000Z".to_string(),
                operator_id: "admin_ops".to_string(),
                operator_name: "运营管理员".to_string(),
                operator_role: "normal_admin".to_string(),
                action: "community_created".to_string(),
                detail: "新增社区 “HighTower KZ 社区”。".to_string(),
            },
            OperationLog {
                id: "log_003".to_string(),
                created_at: "2026-03-06T10:30:00.000Z".to_string(),
                operator_id: "admin_review".to_string(),
                operator_name: "审核管理员".to_string(),
                operator_role: "normal_admin".to_string(),
                action: "whitelist_approved".to_string(),
                detail: "审核通过玩家 KZRunner 的白名单申请。".to_string(),
            },
        ],
    }
}
